### ISSUE TITLE
Request: provide “enter” “leave” and "_type=transition" information for ALL created regions

### ISSUE THREAD

**Issue by goldriver2** [owntracks/talk#106] opened 2020-11-25 13:18 UTC
To help admin understand this request I am Using OwnTracks as a automation system presence location tool. I use this app for 2 specific needs: 
1- to detect the presence of a person in a room OR inside a GPS radius.
2- to determine if someone is approaching or going from a defined place

With the actual OwnTracks messaging system, management "leaving" and "enter" region requires many manipulation as GPS radius region are not treated the same a beacon region

To alleviate the problem I suggest the following 

Actually the iOS app creates a "enter" and "leave" for any created beacon But it does not creates these entries for radius beacon. Furthermore, entering or leaving a beacon is identified as a _type=transition I think that any entering or leaving a GPS radius defined should also be treated as a _type=transition and not _type=location.

_type=Location should only be sent at system defined intervals When the device is on the move.

Thanks for taking this in consideration, let me know if any other informations is required to make this request become a feature

**Comment by jpmens** [comment] 2020-11-25 15:47
I feel this is a duplicate of https://github.com/owntracks/ios/issues/652

**Comment by goldriver2** [comment] 2020-11-25 20:49
You are right, I entered this new one that I think is more realistic and does not change the original goal of the app but clarify the type of events.

I tought I erased #652, I guess I forgot to confirm the deletion, sorry

**Comment by jpmens** [comment] 2020-11-25 21:05
Ok, closing because dup.

**Closed as completed by jpmens** 2020-11-25 21:05 UTC

**Comment by goldriver2** [comment] 2020-11-26 01:29
@jpmens I meant #652 was supposed to be closed but #106 should stay opened.

I think that any entry/leave from any type of regions (beacon or GPS coordinates radius) needs to have a "_type: = transition" with the "event:" set to either enter or leave otherwise, how can we know if you get out of a radius region ?
